### ISSUE TITLE
Different Fingerprint Hash in Private Window

### ISSUE THREAD

**Issue by dr-diffie** [Joe12387/overpoweredjs#1]
Let's try to help each other out. Is the code supposed to produce two different hashes for the same browser in normal and incognito mode? 

![Bildschirmfoto vom 2024-11-21 00-07-53](https://github.com/user-attachments/assets/fa0e6d9d-0d09-402c-ba71-65e28310e002)

**Comment by Joe12387** [comment]
Yes, the fingerprint object changes in different modes, resulting in a different `hash`. It effectively maps the `hash` to the `clusterUUID`, which is supposed to remain constant. `clusterUUID` typically only changes if canvas fingerprinting protections are toggled (for example, Firefox & Safari in private windows). The `hash` effectively just lets us know what record is being referred to behind the scenes.

**Comment by dr-diffie** [comment]
Okay, so to actually track a User accurate, it would be better to log the clusterUUID? If a user abuses a free tier, and we log the hash, it would be enough to just make a private window otherwise?

**Comment by Joe12387** [comment]
Yes, you should use `clusterUUID` as `hash` will change over time. `hash` is only provided for debugging purposes.
